name: Build docs

on:
  push:
    branches: ["main"]
  # Specify to run a workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Gives the workflow permissions to clone the repo and create a page deployment
permissions:
  id-token: write
  pages: write

env:
  PRODUCT: Writerside/hi
  ARTIFACT: webHelpHI2-all.zip

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate the sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://lananovikova10.github.io/intelligent-tools/

      - name: Copy sitemap to artifacts directory
        run: |
          mkdir -p artifacts
          cp ${{ steps.sitemap.outputs.sitemap-path }} artifacts/sitemap.xml

  build-job:
    runs-on: ubuntu-latest
    container: registry.jetbrains.team/p/writerside/builder/writerside-builder:2.1.1471-p3848
    outputs:
      artifact: ${{ steps.generate-artifact.outputs.artifact }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Prepare for build
        run: |
          apt-get update
          apt-get install -y zip
      - name: Build docs and include sitemap.xml
        run: |
          export DISPLAY=:99
          Xvfb :99 &
          /opt/builder/bin/idea.sh helpbuilderinspect -source-dir . -product $PRODUCT --runner github -output-dir artifacts/ || true
          test -e artifacts/$ARTIFACT && echo $ARTIFACT exists
          cd artifacts
          zip -r $ARTIFACT sitemap.xml
        working-directory: ${{ github.workspace }}
      - name: Upload modified documentation artifact
        uses: actions/upload-artifact@v3
        with:
          name: help
          path: artifacts/${{ env.ARTIFACT }}
          retention-days: 7

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Requires the build-job results
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: help
      - name: Unzip artifact
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq ${{ env.ARTIFACT }} -d dir
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dir
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
